-- ==============================================================
-- Backend de Aplicaciones - DDL H2 limpio para Hibernate
-- ==============================================================

-- Limpieza de tablas si existen
DROP TABLE IF EXISTS JUEGOS;
DROP TABLE IF EXISTS PLATAFORMAS;
DROP TABLE IF EXISTS DESARROLLADORES;
DROP TABLE IF EXISTS GENEROS;

-- DESARROLLADORES
CREATE TABLE DESARROLLADORES (
DESA_ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL
);

-- GENEROS
CREATE TABLE GENEROS (
GEN_ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL
);

-- PLATAFORMAS
CREATE TABLE PLATAFORMAS (
PLAT_ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL
);

-- JUEGOS
CREATE TABLE JUEGOS (
JUEGO_ID INT AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(255) NOT NULL,
FECHA_LANZAMIENTO INTEGER,
GENERO_ID INT,
DESARROLLADOR_ID INT,
CLASIFICACION_ESRB VARCHAR(4),
PLATAFORMA_ID INT,
RATING DOUBLE,
JUEGOS_FINALIZADOS INT,
JUGANDO INT,
RESUMEN CLOB NOT NULL,
CONSTRAINT FK_JUEGOS_GENEROS FOREIGN KEY (GENERO_ID) REFERENCES GENEROS(GEN_ID),
CONSTRAINT FK_JUEGOS_DESARROLLADORES FOREIGN KEY (DESARROLLADOR_ID) REFERENCES DESARROLLADORES(DESA_ID),
CONSTRAINT FK_JUEGOS_PLATAFORMAS FOREIGN KEY (PLATAFORMA_ID) REFERENCES PLATAFORMAS(PLAT_ID)
);

-- Índices opcionales
CREATE INDEX IF NOT EXISTS IX_JUEGOS_GENERO ON JUEGOS(GENERO_ID);
CREATE INDEX IF NOT EXISTS IX_JUEGOS_DESA ON JUEGOS(DESARROLLADOR_ID);
CREATE INDEX IF NOT EXISTS IX_JUEGOS_PLATAFORMA ON JUEGOS(PLATAFORMA_ID);
